# Generated by Django 5.2.14 on 2026-05-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpis',
            old_name='project_id',
            new_name='project',
        ),
    ]
