# Generated by Django 5.2.14 on 2026-05-13 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_rename_project_id_kpis_project'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpis',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
