# Generated by Django 5.2.14 on 2026-05-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0003_alter_kpis_project'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpis',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='projects.project'),
        ),
    ]
