# Generated by Django 5.2.14 on 2026-05-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0007_alter_kpi_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='is_min_kpi',
            field=models.BooleanField(default=False),
        ),
    ]
